using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EgyHeart.Migrations
{
    /// <inheritdoc />
    public partial class aa : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "CLINIC_TRANS",
                columns: table => new
                {
                    MASTER_ID = table.Column<double>(type: "float", nullable: false),
                    CHECK_ID = table.Column<double>(type: "float", nullable: false),
                    EX_YEAR = table.Column<double>(type: "float", nullable: false),
                    CLINIC_ID = table.Column<double>(type: "float", nullable: true),
                    EX_DATE = table.Column<DateTime>(type: "datetime", nullable: true),
                    EX_DAY = table.Column<string>(type: "varchar(20)", unicode: false, maxLength: 20, nullable: true),
                    S_CLINIC_ID = table.Column<double>(type: "float", nullable: true),
                    SERV_ID = table.Column<double>(type: "float", nullable: true),
                    EX_PERIOD = table.Column<double>(type: "float", nullable: true),
                    ENTRY_STATUS = table.Column<double>(type: "float", nullable: true),
                    VALUE_SERVICE = table.Column<decimal>(type: "decimal(9,2)", nullable: true),
                    PAT_EXTERNAL = table.Column<double>(type: "float", nullable: true),
                    DR_CODE = table.Column<double>(type: "float", nullable: true),
                    SPECIFIC_CODE = table.Column<double>(type: "float", nullable: true),
                    RECEPT_EMP_CODE = table.Column<double>(type: "float", nullable: true),
                    DR_CODE_CONERTER = table.Column<double>(type: "float", nullable: true),
                    COMP_ID = table.Column<double>(type: "float", nullable: true),
                    PATIENT_VALUE = table.Column<decimal>(type: "decimal(9,2)", nullable: true),
                    CHECK_ID_CANCEL = table.Column<double>(type: "float", nullable: true),
                    EX_INVOICE_NO = table.Column<double>(type: "float", nullable: true),
                    PAT_STATUS = table.Column<double>(type: "float", nullable: true),
                    EX_MONTH = table.Column<double>(type: "float", nullable: true),
                    PAT_EMERG = table.Column<double>(type: "float", nullable: true),
                    QTY = table.Column<double>(type: "float", nullable: true),
                    PAT_TIME = table.Column<DateTime>(type: "datetime", nullable: true),
                    FLAG = table.Column<double>(type: "float", nullable: true),
                    PAT_SER = table.Column<double>(type: "float", nullable: true),
                    PAT_PHAR_NAME = table.Column<string>(type: "varchar(75)", unicode: false, maxLength: 75, nullable: true),
                    CREATE_DATE = table.Column<DateTime>(type: "datetime", nullable: true),
                    PAT_PERC = table.Column<decimal>(type: "decimal(5,2)", nullable: true),
                    MODIFY_DATE_TIME = table.Column<DateTime>(type: "datetime", nullable: true),
                    DR_VAL = table.Column<decimal>(type: "decimal(9,2)", nullable: true),
                    HO_VAL = table.Column<decimal>(type: "decimal(9,2)", nullable: true),
                    DR_VAL_PAT = table.Column<decimal>(type: "decimal(9,2)", nullable: true),
                    HO_VAL_PAT = table.Column<decimal>(type: "decimal(9,2)", nullable: true),
                    BRANCH_ID = table.Column<double>(type: "float", nullable: true),
                    COMP_VALUE = table.Column<decimal>(type: "decimal(9,2)", nullable: true),
                    WAIT_STATUS = table.Column<double>(type: "float", nullable: true),
                    WAIT_RESON = table.Column<double>(type: "float", nullable: true),
                    VIST_CONFIRM = table.Column<double>(type: "float", nullable: true),
                    WAIT_DATE = table.Column<DateTime>(type: "datetime", nullable: true),
                    WAIT_CONV = table.Column<double>(type: "float", nullable: true),
                    WAIT_OTHER = table.Column<double>(type: "float", nullable: true),
                    PAT_ID = table.Column<double>(type: "float", nullable: true),
                    MAIN_INV_NO = table.Column<long>(type: "bigint", nullable: true),
                    USER_CODE_CREATE = table.Column<double>(type: "float", nullable: true),
                    USER_CODE_MODIFY = table.Column<double>(type: "float", nullable: true),
                    CONV_DATE = table.Column<DateTime>(type: "datetime", nullable: true),
                    STOCK_CODE = table.Column<double>(type: "float", nullable: true),
                    SUB_CODE = table.Column<double>(type: "float", nullable: true),
                    MAIN_CODE = table.Column<string>(type: "varchar(10)", unicode: false, maxLength: 10, nullable: true),
                    ITEM_MASTER = table.Column<string>(type: "varchar(30)", unicode: false, maxLength: 30, nullable: true),
                    TRANS_TYPE = table.Column<double>(type: "float", nullable: true),
                    SERIAL = table.Column<double>(type: "float", nullable: true),
                    SER_SYS = table.Column<double>(type: "float", nullable: true),
                    REPLCATE = table.Column<double>(type: "float", nullable: true),
                    RESERVE_FLAG = table.Column<double>(type: "float", nullable: true),
                    UNIT_PRICE = table.Column<decimal>(type: "decimal(9,2)", nullable: true),
                    PAT_AD_DATE = table.Column<DateTime>(type: "datetime", nullable: true),
                    DR_SEND = table.Column<double>(type: "float", nullable: true),
                    EXCHANGE_TYPE = table.Column<double>(type: "float", nullable: true),
                    DOC_NO = table.Column<double>(type: "float", nullable: true),
                    MACHINE = table.Column<double>(type: "float", nullable: true),
                    MCH_HOURS = table.Column<decimal>(type: "decimal(6,2)", nullable: true),
                    ITM_SERV_FLAG = table.Column<double>(type: "float", nullable: true),
                    BENEFICIARY_NAME = table.Column<string>(type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KINSHIP = table.Column<double>(type: "float", nullable: true),
                    DR_ALALYSIS = table.Column<double>(type: "float", nullable: true),
                    NERSE1 = table.Column<double>(type: "float", nullable: true),
                    NERSE2 = table.Column<double>(type: "float", nullable: true),
                    DATE_ANALYSIS = table.Column<DateTime>(type: "datetime", nullable: true),
                    FLAG1 = table.Column<double>(type: "float", nullable: true),
                    SERIVICE_WITH_ITEMS = table.Column<double>(type: "float", nullable: true),
                    DR_SEND_VAL = table.Column<decimal>(type: "decimal(11,2)", nullable: true),
                    FLAG_DR_DISC = table.Column<double>(type: "float", nullable: true),
                    COST_PRICE = table.Column<decimal>(type: "decimal(12,2)", nullable: true),
                    DISCOUNT_VAL = table.Column<decimal>(type: "decimal(11,2)", nullable: true),
                    PIPE_FLAG = table.Column<double>(type: "float", nullable: true),
                    POST_ID = table.Column<double>(type: "float", nullable: true),
                    ITM_BARCODE = table.Column<string>(type: "varchar(50)", unicode: false, maxLength: 50, nullable: true),
                    ENTRY_DATE = table.Column<DateTime>(type: "datetime", nullable: true),
                    DEAL = table.Column<double>(type: "float", nullable: true),
                    APPROVAL_PERIOD = table.Column<double>(type: "float", nullable: true),
                    APPROVAL_DATE = table.Column<DateTime>(type: "datetime", nullable: true),
                    USER_APPROVAL = table.Column<double>(type: "float", nullable: true),
                    ATTENDANCE_SER = table.Column<double>(type: "float", nullable: true),
                    PROCEDURE_ID = table.Column<double>(type: "float", nullable: true),
                    BR_REPLC = table.Column<string>(type: "varchar(20)", unicode: false, maxLength: 20, nullable: true),
                    SEND_FR = table.Column<double>(type: "float", nullable: true),
                    SEND_TO = table.Column<double>(type: "float", nullable: true),
                    ITEM_VISIBLE = table.Column<double>(type: "float", nullable: true),
                    INCOMING_FR = table.Column<double>(type: "float", nullable: true),
                    EXTRA_VAL = table.Column<decimal>(type: "decimal(9,2)", nullable: true),
                    COMP_ID_DTL = table.Column<double>(type: "float", nullable: true),
                    MAIN_INV_NO_ALL = table.Column<int>(type: "int", nullable: true),
                    MAIN_INV_NO_TAX = table.Column<int>(type: "int", nullable: true),
                    MAIN_INV_TOT = table.Column<int>(type: "int", nullable: true),
                    SALSE_PRICE = table.Column<decimal>(type: "decimal(12,3)", nullable: true),
                    DR_DUE_VAL = table.Column<decimal>(type: "decimal(9,2)", nullable: true),
                    PAT_ID_SECTION = table.Column<double>(type: "float", nullable: true),
                    USER_SAFE = table.Column<double>(type: "float", nullable: true),
                    CSH_ORD_NUM = table.Column<double>(type: "float", nullable: true),
                    SESSION_NO = table.Column<double>(type: "float", nullable: true),
                    KNOW_US_FR = table.Column<short>(type: "smallint", nullable: true),
                    EXTRA_VAL2 = table.Column<decimal>(type: "decimal(9,2)", nullable: true),
                    SUP_CODE = table.Column<string>(type: "varchar(6)", unicode: false, maxLength: 6, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CLINIC_TRANS", x => new { x.MASTER_ID, x.CHECK_ID, x.EX_YEAR });
                });

            migrationBuilder.CreateTable(
                name: "PAT",
                columns: table => new
                {
                    BRANCH_ID = table.Column<double>(type: "float", nullable: true),
                    PAT_ID = table.Column<int>(type: "int", nullable: false),
                    PAT_NAME = table.Column<string>(type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    PERSONAL_ID = table.Column<string>(type: "varchar(20)", unicode: false, maxLength: 20, nullable: true),
                    NEW_OLD = table.Column<double>(type: "float", nullable: true),
                    PAT_ADDRESS = table.Column<string>(type: "varchar(255)", unicode: false, maxLength: 255, nullable: true),
                    PAT_TEL = table.Column<string>(type: "varchar(14)", unicode: false, maxLength: 14, nullable: true),
                    PAT_MOBILE = table.Column<string>(type: "varchar(14)", unicode: false, maxLength: 14, nullable: true),
                    BIRTH_DATE = table.Column<DateTime>(type: "datetime", nullable: true),
                    PERSON_KIND = table.Column<double>(type: "float", nullable: true),
                    PAT_DATE = table.Column<DateTime>(type: "datetime", nullable: true),
                    USER_CODE = table.Column<double>(type: "float", nullable: true),
                    PAT_REPEAT = table.Column<double>(type: "float", nullable: true),
                    REPLCATE = table.Column<double>(type: "float", nullable: true),
                    PAT_AGE_TYPE = table.Column<double>(type: "float", nullable: true),
                    PAT_ID_CARD = table.Column<long>(type: "bigint", nullable: true),
                    SHEET_NO = table.Column<double>(type: "float", nullable: true),
                    YOUNG_DAY = table.Column<double>(type: "float", nullable: true),
                    YOUNG_MONTH = table.Column<double>(type: "float", nullable: true),
                    BR_REPLC = table.Column<string>(type: "varchar(20)", unicode: false, maxLength: 20, nullable: true),
                    ENTRY_DATE = table.Column<DateTime>(type: "datetime", nullable: true),
                    PAT_EMAIL = table.Column<string>(type: "varchar(60)", unicode: false, maxLength: 60, nullable: true),
                    NATIONALITY_ID = table.Column<double>(type: "float", nullable: true),
                    RELIGION_ID = table.Column<double>(type: "float", nullable: true),
                    PAT_ID_SER = table.Column<long>(type: "bigint", nullable: true),
                    ID_TYPE = table.Column<double>(type: "float", nullable: true),
                    DOC_COMP_NR = table.Column<string>(type: "varchar(15)", unicode: false, maxLength: 15, nullable: true),
                    DOC_PAT_NR = table.Column<string>(type: "varchar(6)", unicode: false, maxLength: 6, nullable: true),
                    P_DEP = table.Column<string>(type: "varchar(15)", unicode: false, maxLength: 15, nullable: true),
                    P_CRT = table.Column<string>(type: "varchar(15)", unicode: false, maxLength: 15, nullable: true),
                    P_GROUP = table.Column<string>(type: "varchar(15)", unicode: false, maxLength: 15, nullable: true),
                    FINANCE_ID = table.Column<string>(type: "varchar(15)", unicode: false, maxLength: 15, nullable: true),
                    PAT_PASSWORD = table.Column<string>(type: "varchar(15)", unicode: false, maxLength: 15, nullable: true)
                },
                constraints: table =>
                {
                });

            migrationBuilder.CreateTable(
                name: "PAT_ADMISSION",
                columns: table => new
                {
                    MASTER_ID = table.Column<double>(type: "float", nullable: false),
                    EX_YEAR = table.Column<double>(type: "float", nullable: false),
                    BRANCH_ID = table.Column<double>(type: "float", nullable: true),
                    PAT_ID = table.Column<double>(type: "float", nullable: true),
                    DEAL = table.Column<double>(type: "float", nullable: true),
                    PAT_AD_DATE = table.Column<DateTime>(type: "datetime", nullable: true),
                    COMP_ID = table.Column<double>(type: "float", nullable: true),
                    PAT_INTERNAL = table.Column<double>(type: "float", nullable: true),
                    PAT_EXTERNAL = table.Column<double>(type: "float", nullable: true),
                    PAT_EMERGENCY = table.Column<double>(type: "float", nullable: true),
                    PAT_EXIT = table.Column<double>(type: "float", nullable: true),
                    PAT_DATE_EXIT = table.Column<DateTime>(type: "datetime", nullable: true),
                    DECISION_SHEET = table.Column<string>(type: "varchar(255)", unicode: false, maxLength: 255, nullable: true),
                    PAT_CARD_ID = table.Column<double>(type: "float", nullable: true),
                    REPLCATE = table.Column<double>(type: "float", nullable: true),
                    PAT_AD_TIME = table.Column<DateTime>(type: "datetime", nullable: true),
                    MAIN_INV_NO = table.Column<int>(type: "int", nullable: true),
                    MAIN_INV_TOT = table.Column<decimal>(type: "decimal(9,2)", nullable: true),
                    MAIN_INV_DESC = table.Column<string>(type: "varchar(200)", unicode: false, maxLength: 200, nullable: true),
                    PATIENT_VALUE = table.Column<decimal>(type: "decimal(9,2)", nullable: true),
                    COMP_VALUE = table.Column<decimal>(type: "decimal(9,2)", nullable: true),
                    DR_CODE = table.Column<double>(type: "float", nullable: true),
                    DR_VAL = table.Column<decimal>(type: "decimal(10,2)", nullable: true),
                    DR_TAX = table.Column<decimal>(type: "decimal(10,2)", nullable: true),
                    EX_MONTH = table.Column<double>(type: "float", nullable: true),
                    DR_OBTAIN = table.Column<double>(type: "float", nullable: true),
                    DISCOUNT_VAL = table.Column<decimal>(type: "decimal(9,2)", nullable: true),
                    ACC_TRANS_NO = table.Column<long>(type: "bigint", nullable: true),
                    ACC_TRANS_NO2 = table.Column<long>(type: "bigint", nullable: true),
                    SAFE_DOC_NO = table.Column<long>(type: "bigint", nullable: true),
                    SAFE_DOC_NO2 = table.Column<long>(type: "bigint", nullable: true),
                    ARCH = table.Column<string>(type: "varchar(15)", unicode: false, maxLength: 15, nullable: true),
                    ROOM_NO = table.Column<string>(type: "varchar(20)", unicode: false, maxLength: 20, nullable: true),
                    DAYS_NO = table.Column<double>(type: "float", nullable: true),
                    DAYS_VALUE = table.Column<decimal>(type: "decimal(9,2)", nullable: true),
                    FLAG = table.Column<double>(type: "float", nullable: true),
                    DUE_VAL = table.Column<decimal>(type: "decimal(9,2)", nullable: true),
                    EXCHANGE_TYPE = table.Column<double>(type: "float", nullable: true),
                    NOTE = table.Column<string>(type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    AMANAT = table.Column<decimal>(type: "decimal(11,2)", nullable: true),
                    AMANAT_RET = table.Column<decimal>(type: "decimal(11,2)", nullable: true),
                    SAFE_IN_NO1 = table.Column<double>(type: "float", nullable: true),
                    SAFE_IN_NO2 = table.Column<double>(type: "float", nullable: true),
                    AMANAT_RET_PAT = table.Column<decimal>(type: "decimal(11,2)", nullable: true),
                    KASTARA_TOT = table.Column<decimal>(type: "decimal(11,2)", nullable: true),
                    ENAYA_TOT = table.Column<decimal>(type: "decimal(11,2)", nullable: true),
                    JOR_KIED_NO1 = table.Column<double>(type: "float", nullable: true),
                    JOR_KIED_NO2 = table.Column<double>(type: "float", nullable: true),
                    CASH_NO = table.Column<double>(type: "float", nullable: true),
                    STAMP_VAL = table.Column<decimal>(type: "decimal(9,2)", nullable: true),
                    BR_REPLC = table.Column<string>(type: "varchar(20)", unicode: false, maxLength: 20, nullable: true),
                    PAT_CLOSE = table.Column<double>(type: "float", nullable: true),
                    PAY_FLAG = table.Column<double>(type: "float", nullable: true),
                    JOR_KIED_NO3 = table.Column<double>(type: "float", nullable: true),
                    SAFE_DOC_NO3 = table.Column<double>(type: "float", nullable: true),
                    EX_YEAR_TO = table.Column<double>(type: "float", nullable: true),
                    EX_MONTH_TO = table.Column<double>(type: "float", nullable: true),
                    MAIN_CODE = table.Column<string>(type: "varchar(10)", unicode: false, maxLength: 10, nullable: true),
                    SUB_CODE = table.Column<string>(type: "varchar(6)", unicode: false, maxLength: 6, nullable: true),
                    BENEFICIARY_NAME = table.Column<string>(type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    KINSHIP = table.Column<double>(type: "float", nullable: true),
                    INV_TYPE = table.Column<double>(type: "float", nullable: true),
                    ENTRY_DATE = table.Column<DateTime>(type: "datetime", nullable: true),
                    TRANSF_VAL = table.Column<decimal>(type: "decimal(12,2)", nullable: true),
                    POST_ID = table.Column<double>(type: "float", nullable: true),
                    PAT_RELATIONSHIP = table.Column<double>(type: "float", nullable: true),
                    ACC_TRANS_TYPE = table.Column<double>(type: "float", nullable: true),
                    BRNACH_INITIAL = table.Column<double>(type: "float", nullable: true),
                    DR_SEND = table.Column<double>(type: "float", nullable: true),
                    PAY_PAT_TOT = table.Column<decimal>(type: "decimal(11,2)", nullable: true),
                    PAT_ID_SECTION = table.Column<double>(type: "float", nullable: true),
                    WINDOW_FLAG = table.Column<double>(type: "float", nullable: true),
                    CO_NAME_2 = table.Column<string>(type: "varchar(150)", unicode: false, maxLength: 150, nullable: true),
                    SEND_TO = table.Column<double>(type: "float", nullable: true),
                    MAIN_INV_NO_ALL = table.Column<int>(type: "int", nullable: true),
                    PAT_DATE_OUT = table.Column<DateTime>(type: "datetime", nullable: true),
                    PROCEDURE_ID = table.Column<double>(type: "float", nullable: true),
                    PAT_FR = table.Column<double>(type: "float", nullable: true),
                    USER_CODE_CREATE = table.Column<double>(type: "float", nullable: true),
                    USER_CODE_MODIFY = table.Column<double>(type: "float", nullable: true),
                    P_DEP = table.Column<string>(type: "varchar(15)", unicode: false, maxLength: 15, nullable: true),
                    P_CRT = table.Column<string>(type: "varchar(15)", unicode: false, maxLength: 15, nullable: true),
                    P_GROUP = table.Column<string>(type: "varchar(15)", unicode: false, maxLength: 15, nullable: true),
                    FINANCE_ID = table.Column<string>(type: "varchar(15)", unicode: false, maxLength: 15, nullable: true),
                    SEND_FR = table.Column<double>(type: "float", nullable: true),
                    BOOK_ROOM = table.Column<double>(type: "float", nullable: true),
                    MAIN_INV_NO_TAX = table.Column<int>(type: "int", nullable: true),
                    INV_TYPE_TAX = table.Column<double>(type: "float", nullable: true),
                    SEND_TRANSFIR = table.Column<double>(type: "float", nullable: true),
                    M_CODE = table.Column<double>(type: "float", nullable: true),
                    M_CODE_DTL = table.Column<double>(type: "float", nullable: true),
                    OPERATION_CODE = table.Column<double>(type: "float", nullable: true),
                    OPERATION_TYPE = table.Column<double>(type: "float", nullable: true),
                    EXTRA_VAL = table.Column<decimal>(type: "decimal(9,2)", nullable: true),
                    COMP_ID_DTL = table.Column<double>(type: "float", nullable: true),
                    UUID = table.Column<string>(type: "varchar(50)", unicode: false, maxLength: 50, nullable: true),
                    SUBMITID = table.Column<string>(type: "varchar(50)", unicode: false, maxLength: 50, nullable: true),
                    E_INV_STS = table.Column<string>(type: "varchar(1)", unicode: false, maxLength: 1, nullable: true),
                    EINV_DATE = table.Column<DateTime>(type: "datetime", nullable: true),
                    E_INV_ID = table.Column<string>(type: "varchar(50)", unicode: false, maxLength: 50, nullable: true),
                    EINV_ERR = table.Column<string>(type: "varchar(200)", unicode: false, maxLength: 200, nullable: true),
                    TAX_FLAG = table.Column<double>(type: "float", nullable: true),
                    TAX_DATE = table.Column<DateTime>(type: "datetime", nullable: true),
                    PREPAID = table.Column<decimal>(type: "decimal(12,2)", nullable: true),
                    SESSION_NO = table.Column<double>(type: "float", nullable: true),
                    KNOW_US_FR = table.Column<short>(type: "smallint", nullable: true),
                    EXTRA_VAL2 = table.Column<decimal>(type: "decimal(9,2)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PAT_ADMISSION", x => new { x.MASTER_ID, x.EX_YEAR });
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CLINIC_TRANS");

            migrationBuilder.DropTable(
                name: "PAT");

            migrationBuilder.DropTable(
                name: "PAT_ADMISSION");
        }
    }
}
